SET IDENTITY_INSERT [dbo].[Track] ON 

INSERT INTO [dbo].[Track]               --1=Free, 2=Paid, 3=Legacy
([Id], [Name],							  [TrackAvailability],																			   [Url])
VALUES
(1   ,'[Legacy] Lime Rock Park - 2008',						3,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=1'  ),
(2   ,'Virginia International Raceway',						2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=2'  ),
(3   ,'Summit Point Raceway',								1,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=9'  ),
(4   ,'Stafford Motor Speedway',							2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=11' ),
(5   ,'Oxford Plains Speedway',								1,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=12' ),
(6   ,'South Boston Speedway',								1,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=14' ),
(7   ,'Concord Speedway',									1,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=15' ),
(8   ,'USA International Speedway',							1,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=16' ),
(9   ,'Lanier National Speedway',							1,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=17' ),
(10  ,'Road America',										2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=18' ),
(11  ,'Irwindale Speedway',									2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=19' ),
(12  ,'Homestead Miami Speedway',							2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=20' ),
(13  ,'[Legacy] Daytona International Speedway - 2008', 	3,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=26' ),
(14  ,'Richmond Raceway', 									2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=31' ),
(15  ,'Martinsville Speedway',								2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=33' ),
(16  ,'[Legacy] Charlotte Motor Speedway - 2008',			3,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=37' ),
(17  ,'[Legacy] Silverstone Circuit - 2008',				3,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=41' ),
(18  ,'Barber Motorsports Park',							2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=46' ),
(19  ,'WeatherTech Raceway at Laguna Seca',					1,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=47' ),
(20  ,'Sonoma Raceway',										2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=48' ),
(21  ,'Atlanta Motor Speedway',								2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=51' ),
(22  ,'Auto Club Speedway',									2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=225'),
(23  ,'Bark River International Raceway',					2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=396'),
(24  ,'Bristol Motor Speedway',								2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=287'),
(25  ,'Canadian Tire Motorsports Park',						2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=144'),
(26  ,'Cedar Lake Speedway',								2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=387'),
(27  ,'Chicagoland Speedway',								2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=123'),
(28  ,'Chili Bowl',											2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=331'),
(29  ,'Circuit Gilles Villeneuve',							2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=218'),
(30  ,'Circuit Zolder',										2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=199'),
(31  ,'Circuit de Barcelona Catalunya',						2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=345'),
(32  ,'Circuit des 24 Heures du Mans',						2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=268'),
(33  ,'Crandon International Raceway',						2,			'https://members.iracing.com/membersite/member/TrackDetail.do?trkid=382')

SET IDENTITY_INSERT [dbo].[Track] OFF 

SET IDENTITY_INSERT [dbo].[TrackVariant] ON 

INSERT INTO [dbo].[TrackVariant]    --1=Oval, 2=Road, 3=DirtOval, 4=DirtRoad
([Id],  [Name],						[Type], [TrackId])
VALUES
(1,		'Full Course',					2,			1),
(2,		'Chicane',						2,			1),
(3,		'School',						2,			1),
(4,		'Full Course',					2,			2),
(5,		'South',						2,			2),
(6,		'North',						2,			2),
(7,		'Patriot',						2,			2),
(8,		'Grand West',					2,			2),
(9,		'Grand East',					2,			2),
(10,	'Patriot Reverse',				2,			2),
(11,	'Summit Point Raceway',			2,			3),
(12,	'Jefferson Circuit',			2,			3),
(13,	'Short',						2,			3),
(14,	'Jefferson Reverse',			2,			3),
(15,	'School',						2,			3),
(16,	'Full Course',					1,			4),
(17,	'',								3,			5),
(18,	'',								1,			6),
(19,	'',								1,			7),
(20,	'Asphalt',						1,			8),
(21,	'Dirt',							3,			8),
(22,	'Asphalt',						1,			9),
(23,	'Dirt',							3,		    9),
(24,	'Full Course',					2,		   10),
(25,	'Bend',							2,		   10),
(26,	'Figure Eight Jump',			2,		   11),
(27,	'Outer',						1,		   11),
(28,	'Inner',						1,		   11),
(29,	'Outer - Inner',				1,		   11),
(30,	'Figure Eight',					2,		   11),
(31,	'Oval',							1,		   12),
(32,	'Road Course A',				2,		   12),
(33,	'Road Course B',				2,		   12),
(34,	'IndyCar Oval', 				1,		   12),
(35,	'Oval',	 				        1,		   13),
(36,	'Road Course',			        2,		   13),
(37,	'Moto',							2,		   13),
(38,	'Short',						2,		   13),
(39,	'Rallycross Short',				4,		   13),
(40,	'Rallycross Long',				4,		   13),
(41,	'',								1,		   14),
(42,	'',								1,		   15),
(43,	'Oval',							1,		   16),
(44,	'Road Course',					2,		   16),
(45,	'Legends Oval',					1,		   16),
(46,	'Infield Road Course',			2,		   16),
(47,	'Grand Prix',					2,		   17),
(48,	'Historical Grand Prix',		2,		   17),
(49,	'International',				2,		   17),
(50,	'Southern',						2,		   17),
(51,	'National',						2,		   17),
(52,	'Full Course',					2,		   18),
(53,	'Short A',						2,		   18),
(54,	'Short B',						2,		   18),
(55,	'Full Course',					2,		   19),
(56,	'School',						2,		   19),
(57,	'IndyCar 2012-2018',			2,		   20),
(58,	'IndyCar 2008-2011',			2,		   20),
(59,	'Cup Historic',					2,		   20),
(60,	'Cup',							2,		   20),
(61,	'IndyCar pre-2008',				2,		   20),
(62,	'RallyCross',					4,		   20),
(63,	'Oval',							1,		   21),
(64,	'Road Course',					2,		   21),
(65,	'Legends Oval',					2,		   21),
(66,	'Rallycross Short',				4,		   21),
(67,	'Rallycross Long',				4,		   21),
(68,	'Oval',							1,		   22),
(69,	'Competition',					2,		   22),
(70,	'Moto',							2,		   22),
(71,	'Interior',						2,		   22),
(72,	'',								4,		   23),
(73,	'Dirt',							3,		   24),
(74,	'Dual Pit Roads',				1,		   24),
(75,	'Single Pit Road',				1,		   24),
(76,	'',								2,		   25),
(77,	'',								3,		   26),
(78,	'',								1,		   27),
(79,	'',								3,		   28),
(80,	'',								2,		   29),
(81,	'Grand Prix',					2,		   30),
(82,	'Alternate',					2,		   30),
(83,	'Grand Prix',					2,		   31),
(84,	'Rallycross',					4,		   31),
(85,	'National',						2,		   31),
(86,	'Club',							2,		   31),
(87,	'Moto',							2,		   31),
(88,	'Historic',						2,		   31),
(89,	'24 Heures du Mans',			2,		   32),
(90,	'Historic',						2,		   32),
(91,	'Full',							4,		   33),
(92,	'Short',						4,		   33)

SET IDENTITY_INSERT [dbo].[TrackVariant] OFF 


select * from Track
select * from trackvariant

--delete from trackvariant
--delete from Track
