name: Deploy SeasonVoting

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./NgxClient
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run --openssl-legacy-provider build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: S3 Deploy
        uses: Reggionick/s3-deploy@v3.2.0 
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ap-southeast-2 
          delete-removed: true
          no-cache: true
          private: true
          filesToInclude: ".*/*,*/*,**"
        env:
          AWS_DEFAULT_REGION: ap-southeast-2
          AWS_REGION: ap-southeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

